version: '3.7'
services:
  app:
    image: igorhaf/jira:latest
    expose:
      - "8080"
    environment:
      - VIRTUAL_HOST=${HOSTNAME}
    links:
      - postgres:postgres
  postgres:
    image: postgres:12-alpine
    volumes:
      - "./docker/postgres/data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - ${HOST_PORT}:5432
networks:
  default:
    external:
      name: nginx-proxy