version: '3.7'
services:
  app:
    image: igorhaf/jira:latest
    expose:
      - "8080"
    environment:
      - VIRTUAL_HOST=${HOSTNAME}
    links:
      - mysql:mysql
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./docker/mysql/data:/app
    ports:
      - "${HOST_PORT}:3306"
networks:
  default:
    external:
      name: nginx-proxy